# Generated by Django 5.2.17 on 2026-09-26 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chatmessage_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpresence',
            name='current_page',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adminpresence',
            name='identity_avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='adminpresence',
            name='identity_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='adminpresence',
            name='last_page',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, max_length=150)),
                ('identity_name', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('page', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
