# Generated by Django 5.2.17 on 2026-09-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_adminrecoverycodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrecoverycodes',
            name='identity_code_hashes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
