export const farmAdvice = [
  {
    slug: 'twig-borer-check',
    category: 'CROP HEALTH',
    readTime: '5 minute field check',
    title: 'Inspect shaded coffee blocks for twig borer',
    summary: 'A short inspection now can help catch damage before it spreads across the block.',
    image: 'https://address-restaurant2.odoo.com/web/image/1906-689c8b1f/coffee%20man.webp',
    imageAlt: 'Coffee farmer inspecting trees in the field',
    photoCaption: 'FIELD CHECK · COFFEE BLOCKS',
    lead: 'Coffee twig borer damage is easier to manage when affected branches are found early. Walk the shaded and less-ventilated sections of the farm first, and record any trees that need a closer look.',
    steps: [
      'Look for small entry holes, fine boring dust, wilting leaves, or branches that are drying back.',
      'Mark affected trees and prune clearly damaged twigs with clean tools. Remove cut material from the block.',
      'Check nearby trees again on your next farm round and note whether damage is increasing.',
    ],
    note: 'If symptoms are spreading or you are unsure of the pest, share a clear photo with your agronomist before applying any treatment.',
  },
  {
    slug: 'cherry-harvest-quality',
    category: 'HARVEST QUALITY',
    readTime: 'Harvest practice',
    title: 'Keep ripe cherries clean from picking to collection',
    summary: 'Careful picking and clean containers help protect the quality premium in your harvest.',
    image: 'https://address-restaurant2.odoo.com/web/image/2002-f96f6be8/coffee_cherries.webp',
    imageAlt: 'Ripe red coffee cherries ready for careful picking',
    photoCaption: 'HARVEST PRACTICE · RIPE CHERRIES',
    lead: 'Picking ripe cherries selectively and keeping them clean through collection supports a more consistent coffee lot. Agree on collection timing and handling with your buyer before harvest begins.',
    steps: [
      'Pick ripe cherries and leave green or damaged fruit for a later pass where practical.',
      'Use clean containers and keep harvested cherries off bare soil, fuel, and chemical storage areas.',
      'Move the day’s harvest to the agreed collection or processing point without unnecessary delay.',
    ],
    note: 'Buyer quality requirements can differ. Confirm the accepted cherry condition and delivery window before picking at scale.',
  },
  {
    slug: 'mulch-young-trees',
    category: 'SOIL & WATER',
    readTime: 'Seasonal farm care',
    title: 'Mulch young coffee trees before dry spells',
    summary: 'A well-kept mulch ring can help reduce moisture loss and limit weed competition.',
    image: 'https://address-restaurant2.odoo.com/web/image/1948-db6cb14d/Land%20aerial%20view.webp',
    imageAlt: 'Coffee farm landscape in Uganda',
    photoCaption: 'FARM CARE · YOUNG TREES',
    lead: 'Young trees are more exposed to short dry spells and weed competition. Use clean plant material already available on the farm to maintain a mulch ring, while keeping the trunk clear.',
    steps: [
      'Clear aggressive weeds carefully without damaging shallow feeder roots.',
      'Spread dry plant material around the tree, leaving a small open gap around the stem to reduce rot risk.',
      'Check the ring after heavy rain and replenish it with clean material when it thins.',
    ],
    note: 'Avoid moving diseased plant material between blocks. Ask your agronomist about suitable mulch where disease is present.',
  },
]